# Generated by Django 4.0.1 on 2022-01-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_program_userprogram_user_photo_workout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'default_related_name': 'sets'},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'default_related_name': 'workouts'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(help_text='e.g. Weighted Chin-ups', max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='e.g. Warrior Strength Training Routine', max_length=255),
        ),
        migrations.AlterField(
            model_name='set',
            name='training_type',
            field=models.CharField(choices=[('RPT', 'Reverse Pyramid Training'), ('SS', 'Straight Sets')], help_text='e.g. Reverse Pyramid Training (RPT)', max_length=255),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(help_text='e.g. Workout A - Shoulders & Back', max_length=255),
        ),
    ]
