# Generated by Django 4.0.1 on 2022-01-22 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_set_options_alter_workout_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userset',
            old_name='workout',
            new_name='user_workout',
        ),
    ]
